In [22]:
import numpy as np
import pandas as pd


In [23]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [24]:
df=pd.read_csv('covid_toy.csv')

In [25]:
df.sample(3)

age  gender  fever   cough       city has_covid
92   82  Female  102.0  Strong    Kolkata        No
65   69  Female  102.0    Mild  Bangalore        No
64   42    Male  104.0    Mild     Mumbai        No

In [26]:
df['cough'].value_counts()

Mild      62
Strong    38
Name: cough, dtype: int64

In [27]:
df['city'].value_counts()

Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: city, dtype: int64

In [28]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid'])
                                              ,df['has_covid'],test_size=0.2)

In [30]:
x_test

age  gender  fever   cough       city
70   68  Female  101.0  Strong      Delhi
17   40  Female   98.0  Strong      Delhi
19   42  Female    NaN  Strong  Bangalore
80   14  Female   99.0    Mild     Mumbai
88    5  Female  100.0    Mild    Kolkata
95   12  Female  104.0    Mild  Bangalore
31   83    Male  103.0    Mild    Kolkata
42   27    Male  100.0    Mild      Delhi
49   44    Male  104.0    Mild     Mumbai
44   20    Male  102.0  Strong      Delhi
98    5  Female   98.0  Strong     Mumbai
55   81  Female  101.0    Mild     Mumbai
75    5    Male  102.0    Mild    Kolkata
71   75  Female  104.0  Strong      Delhi
47   18  Female  104.0    Mild  Bangalore
62   56  Female  104.0  Strong  Bangalore
86   25    Male  104.0    Mild  Bangalore
37   55    Male  100.0    Mild    Kolkata
2    42    Male  101.0    Mild      Delhi
33   26  Female   98.0    Mild    Kolkata

#  without column Transformer

In [33]:
# adding simple imputer to fever column to handle missing value
si=SimpleImputer()
x_train_fever=si.fit_transform(x_train[['fever']])

# also test data
x_test_fever=si.fit_transform(x_test[['fever']])

x_train_fever.shape


(80, 1)

In [34]:
x_train_fever

array([[100.        ],
       [104.        ],
       [ 99.        ],
       [ 98.        ],
       [101.        ],
       [100.        ],
       [ 99.        ],
       [100.        ],
       [103.        ],
       [ 98.        ],
       [ 99.        ],
       [104.        ],
       [103.        ],
       [100.        ],
       [ 99.        ],
       [102.        ],
       [102.        ],
       [100.69014085],
       [101.        ],
       [104.        ],
       [100.69014085],
       [ 98.        ],
       [100.        ],
       [ 99.        ],
       [100.        ],
       [103.        ],
       [101.        ],
       [ 98.        ],
       [103.        ],
       [100.        ],
       [102.        ],
       [ 99.        ],
       [ 99.        ],
       [100.69014085],
       [101.        ],
       [100.        ],
       [101.        ],
       [ 99.        ],
       [102.        ],
       [101.        ],
       [100.69014085],
       [102.        ],
       [ 98.        ],
       [102

In [36]:
# ordinal encoding on cough
oe=OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough=oe.fit_transform(x_train[['cough']])

#also on test data
x_test_cough=oe.fit_transform(x_test[['cough']])


In [37]:
x_train_cough.shape

(80, 1)

In [45]:
# onehotencoding on gender and city
ohe=OneHotEncoder(drop='first',sparse=False)
x_train_gender_city=ohe.fit_transform(x_train[['gender','city']])

x_test_gender_city=ohe.fit_transform(x_test[['gender','city']])

In [46]:
x_train_gender_city.shape

(80, 4)

In [47]:
x_train_gender_city

array([[0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],


In [48]:
#Extracting age
x_train_age=x_train.drop(columns=['gender','fever','cough','city']).values
x_test_age=x_test.drop(columns=['gender','fever','cough','city']).values

x_train_age.shape


(80, 1)

In [49]:
x_train_age

array([[47],
       [34],
       [59],
       [71],
       [20],
       [19],
       [72],
       [80],
       [16],
       [10],
       [65],
       [54],
       [69],
       [27],
       [22],
       [33],
       [64],
       [23],
       [47],
       [ 6],
       [34],
       [12],
       [11],
       [25],
       [11],
       [73],
       [ 8],
       [24],
       [50],
       [27],
       [74],
       [65],
       [60],
       [84],
       [51],
       [13],
       [38],
       [49],
       [24],
       [14],
       [71],
       [49],
       [64],
       [82],
       [23],
       [51],
       [81],
       [60],
       [10],
       [46],
       [19],
       [83],
       [17],
       [38],
       [34],
       [69],
       [51],
       [31],
       [69],
       [19],
       [65],
       [15],
       [19],
       [73],
       [20],
       [75],
       [16],
       [80],
       [65],
       [66],
       [70],
       [49],
       [82],
       [79],
       [82],
       [42],
       [64],

In [ ]:
# x_train_transformed = np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1)
# also the test data
x_test_transformed = np.concatenate((x_test_age,x_test_fever,x_test_gender_city,x_test_cough),axis=1)

x_train_transformed.shape

## above method is very tedious to do

# Using Column transformer

In [53]:
from sklearn.compose import ColumnTransformer

In [56]:
transformer=ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [57]:
transformer.fit_transform(x_train)

array([[100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  47.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  34.        ],
       [ 99.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  59.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  71.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  20.        ],
       [100.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  19.        ],
       [ 99.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  72.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  80.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          0.    

In [59]:
transformer.fit_transform(x_train).shape

(80, 7)

In [61]:
transformer.transform(x_test).shape

(20, 7)