# Numpy
numerical python-multidimen,nd,1D,2D,3D--nD
advantages
it takes less amount of memory
numpy is must faster 


In [10]:
import numpy as np
li_arr=[i for i in range(0,100)]
np_arr=np.arange(100)
print(li_arr)
print(np_arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [14]:
#size of one element in numpy array
print(np_arr.itemsize)
# size of 100 element
print(np_arr.itemsize * np_arr.size)


4
400


In [15]:
import sys
# size of one element in list
a=10
print(sys.getsizeof(a))
#size of 100 element in list
print(sys.getsizeof(1)*len(li_arr))

28
2800


In [ ]:
# import time
import numpy as np
size=100000
 ## add elements of array a and b
def addition_using_list():
    t1=time.time()
    a=range(size)
    b=range(size)
    c=[a[i]+b[i] for i in range(size)]
    t2=time.time()
    return(t2-t1)
def addition_using_numpy():
    t1=time.time()
    a=np.arange(si)

Numpy(numerical python) is much faster like if we consider two array a=[1,2,3,4,5],b=[1,12,13,14,15]
if we want to add these array then it will take place in only in two Go rather than in one by one
that is called as vectorization is the powerful ability with which we can perform mathematical operation over multiple element at once rather than individual element. we need not to iterate the elemnt(just do a+b):

In [17]:
import numpy as np
#b=np.array([1,2,3,4,5])
#print(b)
a=[1,2,3,4]
b=np.array(a)
print(b)
print(type(b))

[1 2 3 4]
<class 'numpy.ndarray'>


In [18]:
a=[1,2,3,'5',4.5]
b=np.array(a,dtype=int) # default behaviour of numpy it gives the homogenous element

print(b)  # it can be change using dtype

[1 2 3 5 4]


In [20]:
b=np.ones(3,dtype=int)
b

array([1, 1, 1])

In [21]:
b=np.ones((2,3),dtype=int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [24]:
b=np.zeros(3,dtype=int)
b


array([0, 0, 0])

In [25]:
b=np.zeros((3,3),dtype=int)
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [30]:
b=np.full((3,4),(23))
b

array([[23, 23, 23, 23],
       [23, 23, 23, 23],
       [23, 23, 23, 23]])

In [31]:
b=np.full((3,3,4),(22))
b

array([[[22, 22, 22, 22],
        [22, 22, 22, 22],
        [22, 22, 22, 22]],

       [[22, 22, 22, 22],
        [22, 22, 22, 22],
        [22, 22, 22, 22]],

       [[22, 22, 22, 22],
        [22, 22, 22, 22],
        [22, 22, 22, 22]]])

In [32]:
b=np.empty(4)
b

array([4.24399158e-314, 8.48798317e-314, 1.27319747e-313, 1.69759663e-313])

In [33]:
b=np.full(3,4)
b

array([4, 4, 4])

# to create the array using numpy
#1 np.arange(start ,end,step , dtype) method # having control over the steps
#2 np.linspace()  # having control having no that we have to generate
we get evenly spaced value
main diff is in parameter

In [34]:
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
b=np.array([1,2,3,4])
print(b)

[1 2 3 4]


In [36]:
b=np.arange(2,10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
b=np.arange(2,20,2)
b
print(b)

[ 2  4  6  8 10 12 14 16 18]


In [47]:
#np.linspace
b=np.linspace(2,10)
b
# it include the start and end value
# and the step is cal by itself



array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [48]:
print(b[1]-b[0])
print(b[3]-b[2])

0.16326530612244916
0.16326530612244916


In [42]:
b=np.linspace(2,10,5,dtype=int,endpoint=False) # endpoint bydefault True it will include the endpoint
b

array([2, 3, 5, 6, 8])

np.identity(n)-(n*n) matrix
np.eye(m*n)-(m*n) matrix

In [44]:
b=np.identity(3) # we can only get square matrix by giveing only one argument
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
#we can get (m*n) matrix 
b=np.eye(3,4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# to generate array generation

In [46]:
b=np.random.rand(3) # range from 0 to 1
b         # generate random array at every instance 

array([0.42741645, 0.32261849, 0.91992561])

In [49]:
b=np.random.rand(3,4)
b

array([[0.6971868 , 0.79415785, 0.12924631, 0.74319434],
       [0.28106878, 0.63850808, 0.84206843, 0.99478105],
       [0.97401719, 0.16667494, 0.0937282 , 0.64765928]])

In [50]:
# random array from 0 to 10
b=np.random.rand(10)*10
b

array([6.16392844, 1.61372767, 0.37593669, 6.8345203 , 8.85674709,
       8.43059282, 5.41165187, 2.76252321, 0.6598277 , 6.48043476])

In [67]:
b=np.random.randint(10)
b

6

# indexing and slicing

In [1]:
import numpy as np
li=[1,2,3,4,5]
arr=np.array(li)
print(li)
print(arr)


[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [3]:
print(arr.data) #data gives some memory loc
print(arr.shape) # shape no of element
print(arr.dtype) # data type
print(arr.strides) # gives the bytes skipped for the next element

(5,)
int32
(4,)


In [4]:
# for 2d array
li_2d=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d=np.array(li_2d)
print(li_2d)
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [5]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)

(4, 4)
int32
(16, 4)


In [7]:
print(li[3])
print(arr[3])
print(arr[1:3])

4
4
[2 3]


In [9]:
print(li_2d[2][3])
print(arr_2d[2][3])
print(arr_2d[2,3])

12
12
12


In [11]:
# for 2d slicing  
print(li_2d[1][:3])
print(arr_2d[1,:3])

[5, 6, 7]
[5 6 7]


In [15]:
print(li_2d[:3][3])

IndexError: list index out of range

In [16]:
print(li_2d[0:3][2])  # first licing is happen and then the 2nd column will be displayed

[9, 10, 11, 12]


In [19]:
x=li_2d[0:3]
print(x)
y=x[2]
print(y)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]


In [21]:
# we can't access the slicing of array in column wise in normal 2D list but can be in numpy
# and both the row and column slicing can be done in numpy
print(arr_2d[0:3,2]) 

[ 3  7 11]


In [22]:
print(arr_2d[2:4,1:3]) #both row and column in 2d using numpy and it can be possible in normal 2d by iterating
print(li_2d[2:4][1:3]) 

[[10 11]
 [14 15]]
[[13, 14, 15, 16]]


# mathematical op

In [23]:
import numpy as np


In [36]:
li=[1,2,3,4,5]
a=np.random.randint(1,20,5)
b=np.random.randint(1,20,5)
print(a)
print(b)
print(li)

[ 9  3 17  9 10]
[ 8  3 14 17  3]
[1, 2, 3, 4, 5]


In [33]:
li=[i+1 for i in li] # for normal list iteration
li 

[2, 3, 4, 5, 6]

In [37]:
# for numpy array iteration
a=a+1 # numpy use vectarization
a

array([10,  4, 18, 10, 11])

In [38]:
# operation
d=a+b
d

array([18,  7, 32, 27, 14])

In [39]:
c=a+b
c

array([18,  7, 32, 27, 14])

In [40]:
e=a*b
e

array([ 80,  12, 252, 170,  33])

In [41]:
f=a/b
f

array([1.25      , 1.33333333, 1.28571429, 0.58823529, 3.66666667])

In [42]:
x=a//b
x # floor divison

array([1, 1, 1, 0, 3], dtype=int32)

In [43]:
y=a**b # exponantiation not need to iterate each element
y

array([  100000000,          64, -1614004224,  1569325056,        1331],
      dtype=int32)

In [49]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.max())
print(a.argmin()) # it gives the index at which the min is present
print(a.argmax())


[10  4 18 10 11]
53
10.6
4
18
1
2


In [50]:
print(a)
print(b)


[10  4 18 10 11]
[ 8  3 14 17  3]


In [2]:
a>b

NameError: name 'a' is not defined

In [1]:
a<b

NameError: name 'a' is not defined

In [53]:
a==b

array([False, False, False, False, False])

In [54]:
print(np.logical_or(a,b))
print(np.logical_and(a,b))
print(np.logical_not(a))

[ True  True  True  True  True]
[ True  True  True  True  True]
[False False False False False]


In [55]:
a[2]=0
print(np.logical_not(a))

[False False  True False False]


In [56]:
# try for 2d array

