In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [50]:
import numpy as np

In [3]:
#in numpy create a array
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
# creating 0D array
arrZero=np.array(1)
arrZero
print(arrZero)

1


In [6]:
# to check the dimension of the array
arr.ndim

1

In [7]:
arrZero.ndim

0

In [9]:
arr_2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
# no of elements in array
arr_2.size

10

In [11]:
#total memory size by an array
arr_2.nbytes

40

In [12]:
arr.nbytes

20

In [13]:
arrZero.nbytes

4

In [14]:
# find the size of a single element
arr_2.itemsize

4

In [15]:
# to find the data type of the array
arr_2.dtype

dtype('int32')

In [16]:
arr.dtype

dtype('int32')

In [17]:
print(arr_2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [22]:
print(arr_2[0][2])
print(arr_2[1][0])
print(arr_2[0,2])

3
6
3


In [25]:
# to get the specific row of the array
print(arr_2[0,:])
print(arr_2[1,:])

[1 2 3 4 5]
[ 6  7  8  9 10]


In [26]:
arr3=np.array([1,2,3,4,5,6,7,8,9,10])
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr3[1:5]

array([2, 3, 4, 5])

In [29]:
arr3[:5]

array([1, 2, 3, 4, 5])

In [30]:
arr3[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
print(arr3[0,1:4])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [35]:
arr4=arr3.copy()
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
#Zero matrix
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [38]:
#all 1 matrix
np.ones((6,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [39]:
#other matrix
np.full((4,4),34)

array([[34, 34, 34, 34],
       [34, 34, 34, 34],
       [34, 34, 34, 34],
       [34, 34, 34, 34]])

In [43]:
np.full((2,2,3),23)

array([[[23, 23, 23],
        [23, 23, 23]],

       [[23, 23, 23],
        [23, 23, 23]]])

In [16]:
#importing Random
from numpy import random

In [8]:

x=random.randint(100)
x

96

In [54]:
np.random.rand(4,4)

array([[0.62119267, 0.60971731, 0.69148051, 0.70768854],
       [0.74029126, 0.17489758, 0.27623016, 0.51461701],
       [0.25450618, 0.83417154, 0.56743187, 0.33383716],
       [0.27531079, 0.47512044, 0.26976372, 0.73167994]])

In [55]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
#mathematical operations on array
arrm=np.array([12,20,23,21])
arrm

array([12, 20, 23, 21])

In [57]:
#plus operation on array
arrm+15


array([27, 35, 38, 36])

In [58]:
arrm=arrm+2
arrm

array([14, 22, 25, 23])

In [59]:
arrm

array([14, 22, 25, 23])

In [60]:
#sub
#mul
print(arrm)
arrm*10

[14 22 25 23]


array([140, 220, 250, 230])

In [61]:
#division operation
arrm/2

array([ 7. , 11. , 12.5, 11.5])

In [62]:
#adding two arrays
a1=np.array([1,2,3,4,5])
a2=np.array([11,12,13,14,14])
print(a1+a2)

[12 14 16 18 19]


In [63]:
#cos function in array
np.cos(a1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [64]:
print(arr_2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [65]:
# finding min element in the array
np.min(arr_2)

1

In [66]:
#find max element in the given array
np.max(arr_2)

10

In [67]:
#sum of all the element in the arrray
np.sum(arr_2)

55

In [69]:
# iteration 
for x in a1:
    print(x)

1
2
3
4
5


In [70]:
# iteration in 2d
for a in arr_2:
    for b in a:
        print(b)

1
2
3
4
5
6
7
8
9
10


In [17]:
y=random.randint(10)
y

8

In [13]:
y=random.randint(12)
y

2

In [62]:
print(y)

9


In [69]:
np.cos(y)

0.960170286650366

In [18]:
np.sin(y)

NameError: name 'np' is not defined